# Run tests and publish to all registries if successful.
name: Publish
on:
  release:
    types: [published]
jobs:
  test:
    uses: ./.github/workflows/test.yaml
  publish-to-npm:
    needs: test
    uses: ./.github/workflows/publish-to-npm.yaml
    secrets: inherit
  # TODO: Peer packages don’t yet exist so we cannot publish here just yet.
  # publish-to-jsr:
  #   needs: test
  #   uses: ./.github/workflows/publish-to-jsr.yaml
  #   secrets: inherit
